name: sackmman_cart_b2b
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  flutter:
    sdk: flutter
  get: ^4.7.2
  fluttertoast: ^8.2.12
  dropdown_search: ^6.0.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
