// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAai3P4oI5PfM_raNoY5OUkBod_D34M8yY',
    appId: '1:924913075943:web:ffb4c8f03f2611e0c54442',
    messagingSenderId: '924913075943',
    projectId: 'sc-orderapp',
    authDomain: 'sc-orderapp.firebaseapp.com',
    storageBucket: 'sc-orderapp.firebasestorage.app',
    measurementId: 'G-YQXR3Q4QNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWFAUuucwgvZfykUedVnwDQ8Va2wEetE',
    appId: '1:924913075943:android:6d472f9c0b875486c54442',
    messagingSenderId: '924913075943',
    projectId: 'sc-orderapp',
    storageBucket: 'sc-orderapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbRYC7SPoNblxWEQX1Kl8O7uCULSIfde8',
    appId: '1:924913075943:ios:9afc036be5a0e763c54442',
    messagingSenderId: '924913075943',
    projectId: 'sc-orderapp',
    storageBucket: 'sc-orderapp.firebasestorage.app',
    iosBundleId: 'com.sackmman.cart.b2b.app',
  );
}
